// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace agremiacion.Models;

public partial class Cobranza
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public float Monto { get; set; }

    public int Numero { get; set; }

    public int IdFactura { get; set; }

    [JsonIgnore]
    public virtual Factura Factura { get; set; }
}