// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class EstadoPago
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Factura> Factura { get; set; } = new List<Factura>();
}