// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace agremiacion.Models;

public partial class Factura
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public DateTime FechaVencimiento { get; set; }

    public int Numero { get; set; }

    public float ImporteTotal { get; set; }

    public int IdEstadoPago { get; set; }

    public int IdObraSocial { get; set; }

    public virtual ICollection<Cobranza> Cobranza { get; set; } = new List<Cobranza>();

    [JsonIgnore]
    public virtual EstadoPago EstadoPago { get; set; }

    [JsonIgnore]
    public virtual ObraSocial ObraSocial { get; set; }
}