// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace agremiacion.Models;

public partial class ObraSocial
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Factura> Factura { get; set; } = new List<Factura>();
}